<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/styles/default.css'); ?>
        <?php echo $this->headScript(); ?>
    </head> 
    <body>  
        <div id="header">                                                       
            <h1>ZF Basics</h1>                  
        </div>              
        <div id="content">              
            <?php echo $this->layout()->content; ?>
        </div>      
    </body> 
</html>