<?php

namespace Application_Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_CategorieOfertaProxy extends \Application_Model_CategorieOferta implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->_load();
        return parent::setId($id);
    }

    public function getNume()
    {
        $this->_load();
        return parent::getNume();
    }

    public function setNume($nume)
    {
        $this->_load();
        return parent::setNume($nume);
    }

    public function getCircuite()
    {
        $this->_load();
        return parent::getCircuite();
    }

    public function adaugaCircuit(\Application_Model_Circuit $circuit)
    {
        $this->_load();
        return parent::adaugaCircuit($circuit);
    }

    public function eliminaCircuit(\Application_Model_Circuit $circuit)
    {
        $this->_load();
        return parent::eliminaCircuit($circuit);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nume', 'circuite');
    }
}