<?php

namespace Application_Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_OperatorProxy extends \Application_Model_Operator implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->_load();
        return parent::setId($id);
    }

    public function getnume()
    {
        $this->_load();
        return parent::getnume();
    }

    public function setnume($nume)
    {
        $this->_load();
        return parent::setnume($nume);
    }

    public function getEmail()
    {
        $this->_load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->_load();
        return parent::setEmail($email);
    }

    public function getOras()
    {
        $this->_load();
        return parent::getOras();
    }

    public function setOras($oras)
    {
        $this->_load();
        return parent::setOras($oras);
    }

    public function getCodPostal()
    {
        $this->_load();
        return parent::getCodPostal();
    }

    public function setCodPostal($codPostal)
    {
        $this->_load();
        return parent::setCodPostal($codPostal);
    }

    public function getJudet()
    {
        $this->_load();
        return parent::getJudet();
    }

    public function setJudet($judet)
    {
        $this->_load();
        return parent::setJudet($judet);
    }

    public function getStrada()
    {
        $this->_load();
        return parent::getStrada();
    }

    public function setStrada($strada)
    {
        $this->_load();
        return parent::setStrada($strada);
    }

    public function getWebsite()
    {
        $this->_load();
        return parent::getWebsite();
    }

    public function setWebsite($website)
    {
        $this->_load();
        return parent::setWebsite($website);
    }

    public function getPersoanaContact()
    {
        $this->_load();
        return parent::getPersoanaContact();
    }

    public function setPersoanaContact($persoanaContact)
    {
        $this->_load();
        return parent::setPersoanaContact($persoanaContact);
    }

    public function getTelefon()
    {
        $this->_load();
        return parent::getTelefon();
    }

    public function setTelefon($telefon)
    {
        $this->_load();
        return parent::setTelefon($telefon);
    }

    public function getTelefon2()
    {
        $this->_load();
        return parent::getTelefon2();
    }

    public function setTelefon2($telefon2)
    {
        $this->_load();
        return parent::setTelefon2($telefon2);
    }

    public function getLogo()
    {
        $this->_load();
        return parent::getLogo();
    }

    public function setLogo($logo)
    {
        $this->_load();
        return parent::setLogo($logo);
    }

    public function getYahooId()
    {
        $this->_load();
        return parent::getYahooId();
    }

    public function setYahooId($yahooId)
    {
        $this->_load();
        return parent::setYahooId($yahooId);
    }

    public function getDataCreare()
    {
        $this->_load();
        return parent::getDataCreare();
    }

    public function setDataCreare($dataCreare)
    {
        $this->_load();
        return parent::setDataCreare($dataCreare);
    }

    public function getDataUltimaAutentificare()
    {
        $this->_load();
        return parent::getDataUltimaAutentificare();
    }

    public function setDataUltimaAutentificare($dataUltimaAutentificare)
    {
        $this->_load();
        return parent::setDataUltimaAutentificare($dataUltimaAutentificare);
    }

    public function esteActivat()
    {
        $this->_load();
        return parent::esteActivat();
    }

    public function activeaza()
    {
        $this->_load();
        return parent::activeaza();
    }

    public function dezActiveaza()
    {
        $this->_load();
        return parent::dezActiveaza();
    }

    public function getAcceptaEmail()
    {
        $this->_load();
        return parent::getAcceptaEmail();
    }

    public function setAcceptaEmail($acceptaEmail)
    {
        $this->_load();
        return parent::setAcceptaEmail($acceptaEmail);
    }

    public function getSejururiAdaugate()
    {
        $this->_load();
        return parent::getSejururiAdaugate();
    }

    public function adaugaSejur($sejur)
    {
        $this->_load();
        return parent::adaugaSejur($sejur);
    }

    public function getCircuiteAdaugate()
    {
        $this->_load();
        return parent::getCircuiteAdaugate();
    }

    public function adaugaCircuit($circuit)
    {
        $this->_load();
        return parent::adaugaCircuit($circuit);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nume', 'email', 'oras', 'codPostal', 'judet', 'strada', 'website', 'persoanaContact', 'telefon', 'telefon2', 'logo', 'yahooId', 'dataCreare', 'dataUltimaAutentificare', 'activat', 'acceptaEmail', 'circuiteAdaugate');
    }
}