<?php

namespace Application_Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_CircuitProxy extends \Application_Model_Circuit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function adaugaDestinatie(\Application_Model_Destinatie $destinatie)
    {
        $this->_load();
        return parent::adaugaDestinatie($destinatie);
    }

    public function getDestinatii()
    {
        $this->_load();
        return parent::getDestinatii();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->_load();
        return parent::setId($id);
    }

    public function getNume()
    {
        $this->_load();
        return parent::getNume();
    }

    public function setNume($nume)
    {
        $this->_load();
        return parent::setNume($nume);
    }

    public function getPret()
    {
        $this->_load();
        return parent::getPret();
    }

    public function setPret($pret)
    {
        $this->_load();
        return parent::setPret($pret);
    }

    public function getDataAdaugare()
    {
        $this->_load();
        return parent::getDataAdaugare();
    }

    public function setDataAdaugare($dataAdaugare)
    {
        $this->_load();
        return parent::setDataAdaugare($dataAdaugare);
    }

    public function getDataValabilitate()
    {
        $this->_load();
        return parent::getDataValabilitate();
    }

    public function setDataValabilitate($dataValabilitate)
    {
        $this->_load();
        return parent::setDataValabilitate($dataValabilitate);
    }

    public function getDescriere()
    {
        $this->_load();
        return parent::getDescriere();
    }

    public function setDescriere($descriere)
    {
        $this->_load();
        return parent::setDescriere($descriere);
    }

    public function getOperator()
    {
        $this->_load();
        return parent::getOperator();
    }

    public function setOperator($operator)
    {
        $this->_load();
        return parent::setOperator($operator);
    }

    public function esteArhivata()
    {
        $this->_load();
        return parent::esteArhivata();
    }

    public function arhiveaza()
    {
        $this->_load();
        return parent::arhiveaza();
    }

    public function estePromovata()
    {
        $this->_load();
        return parent::estePromovata();
    }

    public function promoveaza()
    {
        $this->_load();
        return parent::promoveaza();
    }

    public function getImagini()
    {
        $this->_load();
        return parent::getImagini();
    }

    public function adaugaImagine(\Application_Model_Imagine $imagine)
    {
        $this->_load();
        return parent::adaugaImagine($imagine);
    }

    public function getCategorieOferta()
    {
        $this->_load();
        return parent::getCategorieOferta();
    }

    public function setCategorieOferta(\Application_Model_CategorieOferta $categorieOferta)
    {
        $this->_load();
        return parent::setCategorieOferta($categorieOferta);
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }

    public function updated()
    {
        $this->_load();
        return parent::updated();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nume', 'pret', 'dataAdaugare', 'dataValabilitate', 'dataModificare', 'descriere', 'promovata', 'arhivata', 'operator', 'imagini', 'categorieOferta', 'destinatii');
    }
}