<?php

namespace Application_Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_DestinatieProxy extends \Application_Model_Destinatie implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getNume()
    {
        $this->_load();
        return parent::getNume();
    }

    public function setNume($nume)
    {
        $this->_load();
        return parent::setNume($nume);
    }

    public function getTara()
    {
        $this->_load();
        return parent::getTara();
    }

    public function getOrase()
    {
        $this->_load();
        return parent::getOrase();
    }

    public function adaugaOras(\Application_Model_Destinatie $oras)
    {
        $this->_load();
        return parent::adaugaOras($oras);
    }

    public function getImagine()
    {
        $this->_load();
        return parent::getImagine();
    }

    public function setImagine($imagine)
    {
        $this->_load();
        return parent::setImagine($imagine);
    }

    public function esteTara()
    {
        $this->_load();
        return parent::esteTara();
    }

    public function setTara(\Application_Model_Destinatie $tara)
    {
        $this->_load();
        return parent::setTara($tara);
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->_load();
        return parent::setId($id);
    }

    public function adaugaCircuit(\Application_Model_Circuit $circuit)
    {
        $this->_load();
        return parent::adaugaCircuit($circuit);
    }

    public function getDestinatieCircuite()
    {
        $this->_load();
        return parent::getDestinatieCircuite();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nume', 'orase', 'tara', 'destinatieCircuite', 'imagine');
    }
}